CREATE DATABASE burgers_db;

USE burgers_db;

CREATE TABLE burgers (
	ID INT(100) AUTO_INCREMENT NOT NULL,
	burger_name VARCHAR(255) NOT NULL,
	devoured TINYINT(1) DEFAULT NULL,
	ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (id)
);